fix(table): avoid cropping the checkbox column
Lundalogik/lime-elements pull request #1549
Opened 2022-02-04 14:41 UTC by LucyChyzhova

fix: https://github.com/Lundalogik/crm-feature/issues/2648
## Review:
- [ ] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [ ] Commits have the correct *type* for the changes made
- [ ] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

2022-02-04 15:45 UTC, anderssonjohan submitted a review, later dismissed

2022-02-07 09:44 UTC, Kiarokh commented on src/components/checkbox/partial-styles/_helper-text.scss
> -    &:focus-visible,
good you removed this one. `focus-within` already should cover `focus-visible`

2022-02-07 09:44 UTC, Kiarokh commented on src/components/checkbox/partial-styles/_helper-text.scss
> -    &:focus-visible,
good you removed this one. `focus-within` already should cover `focus-visible`

2022-02-07 09:44 UTC, Kiarokh commented on src/components/checkbox/partial-styles/_helper-text.scss
> -    &:focus-visible,
good you removed this one. `focus-within` already should cover `focus-visible`

2022-02-07 09:50 UTC, Kiarokh commented
@anderssonjohan can you please approve this PR?
It's approved by me, but I can't do it myself for some reasons. I just see this 👇 
![image](https://user-images.githubusercontent.com/35954987/152764661-1a067714-d65a-4c29-bd88-398d6d75babe.png)

2022-02-07 10:55 UTC, adrianschmidt commented
Testing to see if I have the same problem as Kia…

2022-02-07 10:55 UTC, adrianschmidt requested changes
Testing to see if I have the same problem as Kia…

2022-02-07 13:33 UTC, jgroth approved these changes

2022-02-07 14:44 UTC, merged