fix(progress-flow): make it possible to set an icon color
Lundalogik/lime-elements pull request #1779
Opened 2022-06-29 10:00 UTC by LucyChyzhova

fix: https://github.com/Lundalogik/crm-feature/issues/2841

<img width="534" alt="Screenshot 2022-06-29 at 11 58 27" src="https://user-images.githubusercontent.com/50618208/176409233-86d31799-3e4d-4a89-b347-2ca266e8029d.png">
<img width="529" alt="Screenshot 2022-06-29 at 11 59 38" src="https://user-images.githubusercontent.com/50618208/176409482-20d0cf91-aebd-4763-b1d9-cdaf9db16d41.png">

## Review:
- [ ] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [ ] Commits have the correct *type* for the changes made
- [ ] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

2022-06-30 07:50 UTC, Kiarokh requested changes
Good catch @LucyChyzhova ! 
I guess the history behind this is that just before putting this component for review, we decided to change the variable name from `--progress-flow-icon-color` to `--progress-flow-icon-color--inactive`, to keep it in sync with the rest of variable colors, which also reflect the state `--selected` or `--passed`, etc…

Then we forgot to update the variable name in 3 places: 
1. in the documentation (declaration of those variables) here https://github.com/Lundalogik/lime-elements/blob/5283bd7741dd7bd8938815e6bb708384a87faecb/src/components/progress-flow/progress-flow.scss#L12 
2. in the CSS code here: https://github.com/Lundalogik/lime-elements/blob/5283bd7741dd7bd8938815e6bb708384a87faecb/src/components/progress-flow/progress-flow-item/partial-styles/_colors.scss#L6
3. as well as the variable name in the example here: https://github.com/Lundalogik/lime-elements/blob/5283bd7741dd7bd8938815e6bb708384a87faecb/src/components/progress-flow/examples/progress-flow-colors-css.scss#L17 . 

Normally, this would be a breaking change if we fix those two problems now. But because: 
a. this variable name has never worked from the beginning when this component was added
b. nobody has complained about it or reported it as a bug, 
 
I would argue that it is safe to assume that we can instead fix those 3 problems (documentation, CSS code, & the CSS-coloring example).

What do you think @adrianschmidt ?

2022-06-30 07:53 UTC, Kiarokh commented
I also noticed that we have another typo in the documentations, 
which should separately be fixed from `-passed` to `--passed`
1. here in the documentations: https://github.com/Lundalogik/lime-elements/blob/5283bd7741dd7bd8938815e6bb708384a87faecb/src/components/progress-flow/progress-flow.scss#L10 
2. and also here example: https://github.com/Lundalogik/lime-elements/blob/5283bd7741dd7bd8938815e6bb708384a87faecb/src/components/progress-flow/examples/progress-flow-colors-css.scss#L15

@LucyChyzhova would you please add a new `fix` commit for this as well?

2022-06-30 14:22 UTC, LucyChyzhova commented
> @LucyChyzhova would you please add a new `fix` commit for this as well?

Sure! will be added

2022-07-04 07:37 UTC, adrianschmidt commented
> I also noticed that we have another typo in the documentations, which should separately be fixed from `-passed` to `--passed`
> 
> 1. here in the documentations: https://github.com/Lundalogik/lime-elements/blob/5283bd7741dd7bd8938815e6bb708384a87faecb/src/components/progress-flow/progress-flow.scss#L10
> 2. and also here example: https://github.com/Lundalogik/lime-elements/blob/5283bd7741dd7bd8938815e6bb708384a87faecb/src/components/progress-flow/examples/progress-flow-colors-css.scss#L15
> 
> @LucyChyzhova would you please add a new `fix` commit for this as well?

If the property is correctly named in the code, and this is just a matter of changing the docs, the commit type should be `docs`, not `fix` 😊

2022-07-04 08:44 UTC, Kiarokh submitted a review, later dismissed
great job Lucy! 👏

2022-07-04 09:05 UTC, Kiarokh approved these changes

2022-07-04 09:05 UTC, merged