fix(split-button): don't render the menu if there are no menu items
Lundalogik/lime-elements pull request #1955
Opened 2022-11-16 09:09 UTC by Kiarokh

fix https://github.com/Lundalogik/crm-feature/issues/3086 

## Review:
- [ ] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [ ] Commits have the correct *type* for the changes made
- [ ] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

2022-11-16 09:10 UTC, Befkadu1 submitted a review, later dismissed

2022-11-16 10:09 UTC, Befkadu1 approved these changes

2022-11-16 10:10 UTC, Befkadu1 commented on src/components/split-button/split-button.tsx
> +                    'has-menu': !!this.items.length,
Can we check this one?

2022-11-16 10:11 UTC, Befkadu1 requested changes
Can we check the comment I gave you above

2022-11-16 10:14 UTC, Kiarokh commented on src/components/split-button/split-button.tsx
> +                    'has-menu': !!this.items.length,
what do you mean?

2022-11-16 11:08 UTC, Befkadu1 approved these changes

2022-11-16 11:08 UTC, merged

2022-11-16 11:08 UTC, Befkadu1 commented on src/components/split-button/split-button.tsx
> +                    'has-menu': !!this.items.length,
Sorry you were right!

2022-12-05 14:06 UTC, lime-opensource commented
:tada: This PR is included in version 36.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@limetech/lime-elements/v/36.1.0)
- [GitHub release](https://github.com/Lundalogik/lime-elements/releases/tag/v36.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-01-13 12:23 UTC, lime-opensource commented
:tada: This PR is included in version 36.1.0 :tada:

The release is available on:
- [npm package (@release-36.1.x dist-tag)](https://www.npmjs.com/package/@limetech/lime-elements/v/36.1.0)
- [GitHub release](https://github.com/Lundalogik/lime-elements/releases/tag/v36.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: