Show and hide limel helper line nicely
Lundalogik/lime-elements pull request #2584
Opened 2023-11-02 15:49 UTC by Kiarokh

## Review:
- [ ] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [ ] Commits have the correct *type* for the changes made
- [ ] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

2023-11-03 07:56 UTC, LucyChyzhova requested changes
It doesn’t work if an `Input Field` has auto Completions - it covers the helper line

2023-11-03 13:31 UTC, LucyChyzhova commented on src/components/input-field/input-field.tsx
> +                    hide: hideHelperLine,
yes, I see your point! agree

2023-11-03 15:50 UTC, Kiarokh commented on src/components/input-field/input-field.tsx
> +                class={{
fixed here: https://github.com/Lundalogik/lime-elements/pull/2587

2023-11-06 07:05 UTC, LucyChyzhova submitted a review, later dismissed
🚀

2023-11-06 07:08 UTC, LucyChyzhova commented
We should wait to merge this PR until we implement this logic in other places. So the behaviour is consistent

2023-11-07 10:11 UTC, Kiarokh commented
gonna do it using a CSS only solution: https://github.com/Lundalogik/lime-elements/pull/2591/

2023-11-07 10:11 UTC, closed without merging