chore(menu): be able to use ListSeparator in search result
Lundalogik/lime-elements pull request #2638
Opened 2023-11-29 13:38 UTC by TommyLindh2

A very small typing issue, where we missed that the search results of the `MenuSearcher` type could contains `ListSeparators`

## Review:
- [ ] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [ ] Commits have the correct *type* for the changes made
- [ ] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

2023-11-29 13:42 UTC, adrianschmidt requested changes

2023-11-29 13:42 UTC, adrianschmidt commented on src/components/menu/menu.types.ts
When you fix the lint error, change this commit from a `chore` to a `fix` as well. Then I'll approve 😊

2023-11-29 13:46 UTC, TommyLindh2 commented on src/components/menu/menu.types.ts
I asked chatGPT to get the prefix right, but still don't get it right xD I will fix that

2023-11-29 13:50 UTC, adrianschmidt commented on src/components/menu/menu.types.ts
https://github.com/Lundalogik/lime-elements/blob/next/CONTRIBUTING.md#type

I ought to update that slightly though, because we don't follow it completely. For example, we use chore a bunch for things that does touch src or test files, but that doesn't need a version bump, and also doesn't feel like a refactor…

But at least it's something of a guide.

2023-11-29 13:51 UTC, adrianschmidt approved these changes

2023-11-29 14:54 UTC, adrianschmidt commented
No, since it's just the type of something the consumer will send in to our component, and the type has _expanded_, I think we're good 👍

2023-11-29 14:54 UTC, adrianschmidt approved these changes

2023-11-29 14:54 UTC, merged

2023-11-29 14:57 UTC, lime-opensource commented
:tada: This PR is included in version 37.1.0-next.71 :tada:

The release is available on:
- [npm package (@next dist-tag)](https://www.npmjs.com/package/@limetech/lime-elements/v/37.1.0-next.71)
- [GitHub release](https://github.com/Lundalogik/lime-elements/releases/tag/v37.1.0-next.71)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-02 13:28 UTC, lime-opensource commented
:tada: This PR is included in version 37.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@limetech/lime-elements/v/37.1.0)
- [GitHub release](https://github.com/Lundalogik/lime-elements/releases/tag/v37.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-02 14:19 UTC, lime-opensource commented
:tada: This PR is included in version 37.1.0 :tada:

The release is available on:
- [npm package (@release-37.1.x dist-tag)](https://www.npmjs.com/package/@limetech/lime-elements/v/37.1.0)
- [GitHub release](https://github.com/Lundalogik/lime-elements/releases/tag/v37.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: