feat(chip-set): add delete all chips button
Lundalogik/lime-elements pull request #931
Opened 2020-08-31 14:42 UTC by maltja

fix Lundalogik/crm-feature#1329

## Review:
- [ ] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [ ] Commits have the correct *type* for the changes made
- [ ] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

2020-09-01 07:38 UTC, jgroth requested changes

2020-09-01 07:38 UTC, jgroth commented on src/components/chip-set/chip-set.tsx
> +                onMouseLeave={this.onMouseLeave}
I don't think we need these :slightly_smiling_face: 
We should be able to hide the button with only CSS rules and not have to rely on any JS code

2020-09-01 13:44 UTC, jgroth submitted a review, later dismissed
Good work! :confetti_ball:

2020-09-01 13:49 UTC, jgroth approved these changes

2020-09-01 13:57 UTC, merged

2020-09-02 08:56 UTC, adrianschmidt commented
@jgroth Methinks you didn't test keyboard navigation for this… 😉

You can tab to the clear-button, but there doesn't seem to be any way to actually activate it. I've tried both \<enter\>  and \<space\>.

![image](https://user-images.githubusercontent.com/154725/91960616-6816c500-ed0a-11ea-99ac-1436b0e6e2e1.png)

Also, if you don't hover the component when tabbing to the clear-button, it looks a bit broken:

![image](https://user-images.githubusercontent.com/154725/91960635-706f0000-ed0a-11ea-9be8-ca6fe2675950.png)

I'd be fine with just taking this button out of the tab-flow, since you can already delete the chips by pressing backspace when the input is focused, and unless you have an unreal amount of chips selected, that's pretty fast and easy. That also avoids the downside of having to tab twice to get past this component. What do you say @Kiarokh?

Regardless, it shouldn't be possible to tab to the button when there are no chips selected.

2020-09-02 09:07 UTC, adrianschmidt commented
Found some more small issues:

When disabled, it's still possible to tab to the button:

![image](https://user-images.githubusercontent.com/154725/91961655-c2645580-ed0b-11ea-9e96-2c8dd352639d.png)

When read-only, it's not only possible to tab to the button, but it also becomes visible when any chip is hovered:

![image](https://user-images.githubusercontent.com/154725/91962042-4cacb980-ed0c-11ea-8641-38f9f79e83be.png)

(There's also a small issue with the label cutting part of the chips, both when disabled and when read-only, but I don't think that's got anything to do with this PR. @Kiarokh: If I recall correctly, you moved the label a little bit a while back? It might have happened then. Can you take a look at it?)

2020-09-02 09:10 UTC, Kiarokh commented
@adrianschmidt I think:
* user should be able to tab to the (x) button
* (x) should be none-existing when there are no chips as you said
* (x) should have a `title` and `area-label`

2020-09-02 09:17 UTC, adrianschmidt commented
Ok. I'll add the above in an issue.

2020-09-02 10:16 UTC, jgroth commented
> @jgroth Methinks you didn't test keyboard navigation for this… 

That is a fair assumption! :smile:

2020-09-02 12:10 UTC, Kiarokh commented
@adrianschmidt I think we have addressed issues above here: https://github.com/Lundalogik/lime-elements/pull/938

2020-09-02 12:11 UTC, Kiarokh commented
oops, except the keyboard interactions (**Enter** / Space)