Add leading search icon to chips input
Lundalogik/lime-elements pull request #939
Opened 2020-09-03 09:03 UTC by Kiarokh

fix: https://github.com/Lundalogik/crm-feature/issues/1341
fix: https://github.com/Lundalogik/crm-feature/issues/1302

## Review:
- [ ] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [ ] Commits have the correct *type* for the changes made
- [ ] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

2020-09-04 08:02 UTC, jgroth requested changes

2020-09-04 09:18 UTC, Kiarokh commented on src/components/chip-set/chip-set.tsx
> +                    'is-used-as-search': this.leadingSearchIcon !== null,
agreed

2020-09-04 09:19 UTC, Kiarokh commented on src/components/chip-set/chip-set.tsx
> +    public leadingSearchIcon: string = null;
agree

2020-09-07 11:30 UTC, jgroth approved these changes

2020-09-07 14:07 UTC, jgroth approved these changes

2020-09-07 14:13 UTC, merged